version: '3.8'

services:
  crawler-node-1:
    build:
      context: ./crawler-node
      dockerfile: Dockerfile
    container_name: crawler-node-1
    ports:
      - "5001:5000"
    networks:
      - crawler-network
    restart: unless-stopped
    volumes:
      - ./crawler-node:/app
    # Playwright-specific configurations
    security_opt:
      - seccomp=./seccomp_profile.json
    ipc: host  # Recommended for Chromium
    # Environment variables
    environment:
      - NODE_ENV=production
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

networks:
  crawler-network:
    driver: bridge